### ISSUE TITLE
Set up CI.

### ISSUE THREAD

**Issue by aklagoo** [aklagoo/vv-backend#3]
## Tasks

- [x] Create an empty workflow.
- [x] Add test command.
- [x] Test if it works.
